"""Registry of deployable components (``components/*/component.yaml``).

    uv run python tools/components.py list            one line per component
    uv run python tools/components.py check           validate every manifest against the code
    uv run python tools/components.py matrix [names]  GitHub Actions matrix JSON (CI image builds)
    uv run python tools/components.py show <name>     one manifest as JSON
    uv run python tools/components.py render-compose [--check]
                                                     regenerate deploy/compose.production.yml
    uv run python tools/components.py version <name|platform>
                                                     the version in the source tree
    uv run python tools/components.py bundle <name|platform> <out.tgz> [--version X.Y.Z]
                                                     the deploy bundle the host deployer installs

A manifest describes what the platform needs to build, run and release a component:
its package and console entry point, image, compose services and their commands,
the providers it ships, the secret *names* it reads, and its release class
(``rollback``: auto | writer | forward-only).

Versions live with the code: ``[project].version`` for Python components,
``package.json`` for static ones, and ``deploy/component.yaml`` for the platform.
"""

from __future__ import annotations

import ast
import gzip
import io
import json
import re
import subprocess
import sys
import tarfile
import tomllib
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, model_validator

REPO = Path(__file__).resolve().parents[1]
REGISTRY = "ghcr.io/arjundoshi221"
BASE_COMPOSE = REPO / "deploy" / "compose.base.yml"
RENDERED_COMPOSE = REPO / "deploy" / "compose.production.yml"
COMPOSE_HEADER = """# GENERATED by `uv run python tools/components.py render-compose`; do not edit.
# Source: deploy/compose.base.yml plus components/*/deploy/compose.yaml. The legacy
# release path (deploy-release.sh) deploys this merged file; the per-component deployer
# merges the same sources itself.
"""
# Keys a component fragment may not set on a service (platform-owned or unsafe).
FORBIDDEN_SERVICE_KEYS = frozenset(
    {"privileged", "network_mode", "pid", "ipc", "cap_add", "container_name", "build"}
)
NAME = re.compile(r"^[a-z][a-z0-9-]{1,40}$")
VERSION = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-rc\.\d+)?$")
PLATFORM_MANIFEST = REPO / "deploy" / "component.yaml"
# Platform bundle paths installed executable (the sudoers entry points and host tools).
EXECUTABLE_DIRS = ("deploy/scripts/", "deploy/host/")


class Service(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    command: list[str] = Field(default_factory=list)
    mode: Literal["daemon", "run-on-deploy", "scheduled"] = "daemon"
    profile: str | None = None
    schedule: str | None = None


class Health(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: Literal["http", "heartbeat", "running", "exit-zero", "compose"]
    url: str | None = None
    service: str | None = None
    max_age: int | None = None


class Platform(BaseModel):
    model_config = ConfigDict(extra="forbid")

    image_var: str
    rollback: Literal["auto", "writer", "forward-only"]
    data_contract: int | None = None
    user: str
    user_exception: str | None = None
    logs: str

    @model_validator(mode="after")
    def _consistent(self) -> Platform:
        if self.rollback == "writer" and self.data_contract is None:
            raise ValueError("writers declare a data_contract (bump it when written data changes)")
        if self.user == "0" and not self.user_exception:
            raise ValueError("a root container needs a user_exception explaining why")
        return self


class Component(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_: Literal[1] = Field(alias="schema")
    name: str
    kind: Literal["python", "static"]
    package: str | None = None
    summary: str
    image: str
    dockerfile: str
    entrypoint: str | None = None
    providers: list[str] = Field(default_factory=list)
    secrets: list[str] = Field(default_factory=list)
    services: list[Service]
    health: Health
    platform: Platform

    @property
    def root(self) -> Path:
        return REPO / "components" / self.name

    @property
    def compose_fragment(self) -> Path:
        return self.root / "deploy" / "compose.yaml"


class PlatformManifest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_: Literal[1] = Field(alias="schema")
    name: Literal["platform"]
    version: str
    summary: str


def load_platform() -> PlatformManifest:
    return PlatformManifest.model_validate(
        yaml.safe_load(PLATFORM_MANIFEST.read_text(encoding="utf-8"))
    )


def load_all() -> list[Component]:
    components = []
    for path in sorted((REPO / "components").glob("*/component.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        components.append(Component.model_validate(data))
    return components


def _provider_tuple(component: Component) -> list[str] | None:
    """The ``PROVIDERS`` tuple in the component's providers.py, if it has one."""
    if not component.package:
        return None
    pkg = component.name.replace("-", "_")
    path = component.root / "src" / "factorlab" / "components" / pkg / "providers.py"
    if not path.exists():
        return None
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.AnnAssign | ast.Assign):
            targets = [node.target] if isinstance(node, ast.AnnAssign) else node.targets
            if any(isinstance(t, ast.Name) and t.id == "PROVIDERS" for t in targets):
                return list(ast.literal_eval(node.value))
    return None


def problems(components: list[Component]) -> list[str]:
    found: list[str] = []
    seen_services: dict[str, str] = {}
    for c in components:
        where = f"components/{c.name}/component.yaml"
        if not NAME.match(c.name) or not c.root.is_dir():
            found.append(f"{where}: name must match its directory")
        if c.image != f"{REGISTRY}/factorlab-{c.name}":
            found.append(f"{where}: image must be {REGISTRY}/factorlab-{c.name}")
        expected_var = f"FACTORLAB_{c.name.upper().replace('-', '_')}_IMAGE"
        if c.platform.image_var != expected_var:
            found.append(f"{where}: platform.image_var must be {expected_var}")
        dockerfile = REPO / c.dockerfile
        if not dockerfile.is_file():
            found.append(f"{where}: {c.dockerfile} is missing")
        if not dockerfile.with_name(dockerfile.name + ".dockerignore").is_file():
            found.append(f"{where}: {c.dockerfile}.dockerignore is missing")
        found += fragment_problems(c)
        if not VERSION.match(version_of(c)):
            found.append(f"{where}: version {version_of(c)!r} is not X.Y.Z")
        for service in c.services:
            if service.name in seen_services:
                found.append(
                    f"{where}: service {service.name} also belongs to {seen_services[service.name]}"
                )
            seen_services[service.name] = c.name
        if c.kind != "python":
            continue
        pyproject = c.root / "pyproject.toml"
        project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
        if c.package != project["name"]:
            found.append(f"{where}: package must be {project['name']}")
        if c.entrypoint not in project.get("scripts", {}):
            found.append(f"{where}: entrypoint {c.entrypoint} is not a [project.scripts] entry")
        if dockerfile.is_file() and f"--package {c.package}" not in dockerfile.read_text("utf-8"):
            found.append(f"{where}: {c.dockerfile} must install --package {c.package}")
        declared = sorted(
            d.split(">")[0].split("[")[0].removeprefix("factorlab-provider-").replace("-", "_")
            for d in project.get("dependencies", [])
            if d.startswith("factorlab-provider-")
        )
        shipped = _provider_tuple(c)
        if sorted(c.providers) != declared:
            found.append(
                f"{where}: providers {sorted(c.providers)} != provider dependencies {declared}"
            )
        if shipped is not None and sorted(shipped) != sorted(c.providers):
            found.append(
                f"{where}: providers.py PROVIDERS {sorted(shipped)} != manifest "
                f"{sorted(c.providers)}"
            )
    if not VERSION.match(load_platform().version):
        found.append(f"deploy/component.yaml: version {load_platform().version!r} is not X.Y.Z")
    return found


def fragment_problems(c: Component) -> list[str]:
    """Platform policy for a component's compose fragment."""
    where = f"components/{c.name}/deploy/compose.yaml"
    if not c.compose_fragment.is_file():
        return [f"{where} is missing"]
    services = (yaml.safe_load(c.compose_fragment.read_text(encoding="utf-8")) or {}).get(
        "services", {}
    )
    found = []
    if sorted(services) != sorted(s.name for s in c.services):
        found.append(
            f"{where}: services {sorted(services)} != manifest {sorted(s.name for s in c.services)}"
        )
    for name, svc in services.items():
        if not str(svc.get("image", "")).startswith("${" + c.platform.image_var):
            found.append(f"{where}: {name}.image must start with ${{{c.platform.image_var}")
        if "logging" not in svc:
            found.append(f"{where}: {name} needs a logging block (json-file caps)")
        if bad := sorted(FORBIDDEN_SERVICE_KEYS & set(svc)):
            found.append(f"{where}: {name} may not set {bad}")
        for port in svc.get("ports", []):
            if not str(port).startswith("127.0.0.1:"):
                found.append(f"{where}: {name} port {port} must bind 127.0.0.1 only")
        for volume in svc.get("volumes", []):
            if "docker.sock" in str(volume):
                found.append(f"{where}: {name} may not mount the Docker socket")
    return found


def render_compose(components: list[Component]) -> str:
    """Merge the base and every fragment into one Compose model (anchors expanded)."""
    base = yaml.safe_load(BASE_COMPOSE.read_text(encoding="utf-8"))
    merged: dict = {"name": base["name"], "services": {}}
    for source in [base] + [
        yaml.safe_load(c.compose_fragment.read_text(encoding="utf-8"))
        for c in components
        if c.compose_fragment.is_file()
    ]:
        for name, service in (source.get("services") or {}).items():
            if name in merged["services"]:
                raise ValueError(f"service {name} is defined twice")
            merged["services"][name] = service
    merged["networks"] = base.get("networks", {})
    merged["volumes"] = base.get("volumes", {})
    return COMPOSE_HEADER + yaml.safe_dump(
        merged, sort_keys=False, width=100, default_flow_style=False
    )


def version_of(component: Component) -> str:
    """The component's version as declared in its source tree."""
    if component.kind == "static":
        return json.loads((component.root / "package.json").read_text(encoding="utf-8"))["version"]
    pyproject = tomllib.loads((component.root / "pyproject.toml").read_text(encoding="utf-8"))
    return pyproject["project"]["version"]


def _source_files(*paths: str) -> list[str]:
    """Files git would ship under ``paths``: tracked or new, never ignored (no local secrets)."""
    listed = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", *paths],
        cwd=REPO,
        capture_output=True,
        check=True,
    ).stdout
    return sorted({p for p in listed.decode("utf-8").split("\0") if p and (REPO / p).is_file()})


def _read_source(path: Path) -> bytes:
    data = path.read_bytes()
    # A Windows checkout (core.autocrlf) must not ship CRLF shell scripts to Linux.
    return data if b"\0" in data else data.replace(b"\r\n", b"\n")


def component_bundle(component: Component, version: str) -> dict[str, bytes]:
    """``component.json`` (the manifest plus version) and the compose fragment."""
    manifest = component.model_dump(mode="json", by_alias=True) | {"version": version}
    return {
        "component.json": (json.dumps(manifest, indent=2) + "\n").encode("utf-8"),
        "compose.yaml": _read_source(component.compose_fragment),
    }


def platform_bundle(components: list[Component]) -> dict[str, bytes]:
    """``deploy/`` plus every component's fragment, used to seed components on the host."""
    entries = {path: _read_source(REPO / path) for path in _source_files("deploy")}
    for component in components:
        for name, data in component_bundle(component, version_of(component)).items():
            entries[f"components/{component.name}/{name}"] = data
    return entries


def write_bundle(entries: dict[str, bytes], out: Path) -> None:
    """A reproducible .tgz: sorted entries, zero mtimes, root-owned, fixed modes."""
    out.parent.mkdir(parents=True, exist_ok=True)
    with (
        out.open("wb") as raw,
        gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as zipped,
        tarfile.open(fileobj=zipped, mode="w", format=tarfile.PAX_FORMAT) as archive,
    ):
        for name in sorted(entries):
            info = tarfile.TarInfo(name)
            info.size = len(entries[name])
            info.mode = 0o755 if name.startswith(EXECUTABLE_DIRS) else 0o644
            info.uname = info.gname = "root"
            archive.addfile(info, io.BytesIO(entries[name]))


def build_bundle(
    name: str, out: Path, components: list[Component], expected: str | None = None
) -> str:
    """Write ``name``'s deploy bundle to ``out`` and return its version."""
    if name == "platform":
        version, entries = load_platform().version, platform_bundle(components)
    else:
        matches = [c for c in components if c.name == name]
        if not matches:
            raise ValueError(f"unknown component {name}")
        version = version_of(matches[0])
        entries = component_bundle(matches[0], version)
    if expected is not None and expected != version:
        raise ValueError(f"{name} is {version} in the source tree, not {expected}")
    write_bundle(entries, out)
    return version


def matrix(components: list[Component], names: list[str] | None = None) -> dict:
    chosen = [c for c in components if not names or c.name in names]
    return {
        "include": [
            {
                "component": c.name,
                "dockerfile": c.dockerfile,
                "kind": c.kind,
                "entrypoint": c.entrypoint or "",
            }
            for c in chosen
        ]
    }


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    command = args[0] if args else "list"
    components = load_all()
    if command == "list":
        for c in components:
            services = ", ".join(s.name for s in c.services)
            print(f"{c.name:18} {c.kind:7} {c.platform.rollback:13} {services}")
        return 0
    if command == "check":
        issues = problems(components)
        for issue in issues:
            print(issue, file=sys.stderr)
        if not issues:
            print(f"{len(components)} component manifests are consistent")
        return 1 if issues else 0
    if command == "matrix":
        print(json.dumps(matrix(components, args[1:] or None)))
        return 0
    if command == "render-compose":
        text = render_compose(components)
        if "--check" in args:
            current = (
                RENDERED_COMPOSE.read_text(encoding="utf-8") if RENDERED_COMPOSE.exists() else ""
            )
            if current != text:
                print(
                    f"{RENDERED_COMPOSE.relative_to(REPO)} is stale; run render-compose",
                    file=sys.stderr,
                )
                return 1
            print(f"{RENDERED_COMPOSE.relative_to(REPO)} is current")
            return 0
        RENDERED_COMPOSE.write_text(text, encoding="utf-8")
        print(f"wrote {RENDERED_COMPOSE.relative_to(REPO)}")
        return 0
    if command == "version" and len(args) == 2:
        if args[1] == "platform":
            print(load_platform().version)
            return 0
        match = [c for c in components if c.name == args[1]]
        if not match:
            print(f"unknown component {args[1]}", file=sys.stderr)
            return 2
        print(version_of(match[0]))
        return 0
    if command == "bundle" and len(args) in {3, 5}:
        expected = None
        if len(args) == 5:
            if args[3] != "--version":
                print(__doc__, file=sys.stderr)
                return 2
            expected = args[4]
        try:
            version = build_bundle(args[1], Path(args[2]), components, expected)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            return 1
        print(f"wrote {args[2]} ({args[1]} {version})")
        return 0
    if command == "show" and len(args) == 2:
        match = [c for c in components if c.name == args[1]]
        if not match:
            print(f"unknown component {args[1]}", file=sys.stderr)
            return 2
        print(match[0].model_dump_json(indent=2, by_alias=True))
        return 0
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
