"""Generate .env.example from the code (settings models, direct env reads, manifests).

    uv run python tools/env_example.py            write .env.example
    uv run python tools/env_example.py --check    fail if .env.example is stale (CI)

Three sources, so the example cannot drift from what the code reads:

1. every ``FactorLabSettings`` subclass: its fields' variables and defaults, with
   ``Secret("NAME")`` fields listed as secrets;
2. every variable product code reads directly (``os.getenv("X")``, ``os.environ["X"]``,
   ``os.environ.get("X")``; found by AST scan);
3. every secret name a component manifest declares (``components/*/component.yaml``) or
   the code reads by name (``get_secret("NAME")``).

It lists names and defaults only; values never appear. The file is for local development
(``uv run --env-file .env ...``); production reads settings from compose and secrets from
the runtime secret volumes.
"""

from __future__ import annotations

import ast
import importlib
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / ".env.example"
HEADER = """\
# GENERATED by `uv run python tools/env_example.py`; do not edit by hand.
# Local development only: copy to .env and run with `uv run --env-file .env ...`.
# Production reads settings from compose (deploy/, components/*/deploy/compose.yaml) and
# secrets from the Cloudflare secret stores through the runtime secret volumes.
"""


def product_files() -> list[Path]:
    return sorted(
        p
        for group in ("libs", "providers", "components")
        for p in (REPO / group).glob("*/src/factorlab/**/*.py")
        if "__pycache__" not in p.parts
    )


def _module_name(path: Path) -> str:
    parts = list(path.relative_to(REPO).parts)
    src = parts.index("src")
    names = parts[src + 1 :]
    names[-1] = names[-1].removesuffix(".py")
    if names[-1] == "__init__":
        names.pop()
    return ".".join(names)


def settings_models() -> list[type]:
    from factorlab.core.settings import FactorLabSettings

    for path in product_files():
        text = path.read_text(encoding="utf-8")
        if "(FactorLabSettings)" in text:
            importlib.import_module(_module_name(path))

    def walk(cls: type) -> list[type]:
        return [cls, *(c for sub in cls.__subclasses__() for c in walk(sub))]

    product = {_module_name(path) for path in product_files()}
    # Only models defined in product code (tests define their own subclasses).
    return sorted(
        (
            c
            for c in walk(FactorLabSettings)
            if c is not FactorLabSettings and c.__module__ in product
        ),
        key=lambda c: (c.__module__, c.__name__),
    )


def model_lines(model: type) -> tuple[list[str], set[str]]:
    from factorlab.core.settings import Secret

    prefix = str(model.model_config.get("env_prefix", ""))
    lines, secrets = [], set()
    for name, field in model.model_fields.items():
        secret = next((m for m in field.metadata if isinstance(m, Secret)), None)
        alias = field.validation_alias if isinstance(field.validation_alias, str) else None
        variable = (alias or f"{prefix}{name}").upper()
        if secret is not None:
            secrets.add(secret.name)
            continue
        default = field.get_default(call_default_factory=True)
        value = "" if default is None else str(default)
        lines.append(f"# {variable}={value}")
    return lines, secrets


def direct_reads() -> dict[str, list[str]]:
    """Variable -> the modules that read it directly."""
    found: dict[str, set[str]] = {}
    for path in product_files():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            name = None
            if isinstance(node, ast.Call) and node.args and isinstance(node.args[0], ast.Constant):
                target = ast.unparse(node.func)
                if target in {"os.getenv", "os.environ.get", "getenv"}:
                    name = node.args[0].value
            elif (
                isinstance(node, ast.Subscript)
                and ast.unparse(node.value) == "os.environ"
                and isinstance(node.slice, ast.Constant)
            ):
                name = node.slice.value
            if isinstance(name, str) and name.isupper():
                found.setdefault(name, set()).add(path.relative_to(REPO).parts[1])
    return {k: sorted(v) for k, v in sorted(found.items())}


def secret_reads() -> dict[str, list[str]]:
    """Secret name -> module groups calling ``get_secret("NAME")`` with a literal name."""
    found: dict[str, set[str]] = {}
    for path in product_files():
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if (
                isinstance(node, ast.Call)
                and node.args
                and ast.unparse(node.func).endswith("get_secret")
                and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[0].value, str)
                and node.args[0].value.isupper()
            ):
                found.setdefault(node.args[0].value, set()).add(path.relative_to(REPO).parts[1])
    return {k: sorted(v) for k, v in sorted(found.items())}


def manifest_secrets() -> dict[str, list[str]]:
    found: dict[str, set[str]] = {}
    for path in sorted((REPO / "components").glob("*/component.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        for name in data.get("secrets", []):
            found.setdefault(name, set()).add(data["name"])
    return {k: sorted(v) for k, v in sorted(found.items())}


def render() -> str:
    out = [HEADER]
    model_secrets: set[str] = set()
    model_vars: set[str] = set()
    sections = []
    for model in settings_models():
        lines, secrets = model_lines(model)
        model_secrets |= secrets
        model_vars |= {line[2:].split("=", 1)[0] for line in lines}
        sections.append((f"{model.__name__} ({model.__module__})", lines))
    secrets = manifest_secrets()
    for name, users in secret_reads().items():
        secrets[name] = sorted(set(secrets.get(name, [])) | set(users))
    for name in model_secrets:
        secrets.setdefault(name, [])
    out.append(
        "\n# -- Secrets (names only; production: Cloudflare secret store) " + "-" * 20 + "\n"
    )
    for name, users in sorted(secrets.items()):
        out.append(f"{name}=" + (f"   # {', '.join(users)}" if users else "") + "\n")
    for title, lines in sections:
        out.append(f"\n# -- {title} " + "-" * max(4, 74 - len(title)) + "\n")
        out.extend(f"{line}\n" for line in lines)
    direct = {k: v for k, v in direct_reads().items() if k not in model_vars and k not in secrets}
    out.append(
        "\n# -- Read directly by product code (module groups in brackets) " + "-" * 18 + "\n"
    )
    for name, users in direct.items():
        out.append(f"# {name}=   [{', '.join(users)}]\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    text = render()
    if "--check" in args:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(
                ".env.example is stale; run `uv run python tools/env_example.py`", file=sys.stderr
            )
            return 1
        print(".env.example is current")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
